### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by alsonicr** [LAAC-LSCP/ChildRecordsR#20]
Here you can write all the potential changes we should provide before the next version is released.

**Comment by alecristia** [comment]
### outward facing things

it may be easier for users if functions are labeled homogeneously

so assuming find.rating.segment stays the same, then:

- aggregate.rating OK
- reliability --> get.reliability
- SDT.raterData --> get.classification
- raterComparaison--> compare.rating

### intermediate things (that users see as printouts and/or in the help

- Record span -- in aggregate_rating.R -- not sure what this means; do we mean how long the recordings span? or rather how long the annotations span? if the latter, let's change this to: "Annotations span"
- length of recording annotation -- in aggregate_rating.R -- how is different from the previous one?
- harmonize how the class is referred to, eg ChildRecordings : a ChildRecordings class -- should it be ChildRecordingsData class?

### internal things (low priority to these changes as they won't affect typical users)

- file_openner.R --> file_opener.R
- erro.convertion --> error.conversion
- add explanations & comments to data_to_OneHotEnc.R?
- convertor_long_cut.R is using a for loop, this could be done using a matrix & it would be a lot faster
- extractDataCR.R is using a for loop, this could be done using a matrix & it would be a lot faster

**Comment by alsonicr** [comment]
> aggregate.rating OK
> reliability --> get.reliability
> SDT.raterData --> get.classification
> raterComparaison--> compare.rating


I found that in a R function the "." is use to creat a method for a class.

What do you think of  : 
- aggregateRating or aggregate
- getReliability
- getClassification
- compareRating

**Comment by alsonicr** [comment]
@alecristia I m pretty sure i change function name long ago it seem that some of the merging change it.

I'm going to check every comment you made to be sure

**Comment by alsonicr** [comment]
> in find_rating_segment.R what does this line mean: " time = seq(range_from-1000, range_to+1000, 1000)" -- does it mean that annotations that do not begin or end within one second of the window will not be discovered?
> find_rating_segment.R needs more comments, I personally cannot follow all the logic -- for instance, why "tmp$true_onset <- true_onset+1000"?


@alecristia 
I will add comment on it .

First point : I need a larger time window because I can tell that on its two segments they can be defined as "without annotator". This can be useful for the `diff` function in line 140. If the annotations start at the first line then the diff will not notice the annotations. 

Second point : This is because of the way `diff` works, the difference will be noted from the previous segment before the annotators are identified.  So I have to identify the next segment to be correct.

**Comment by alecristia** [comment]
any open items in this issue have been exported elsewhere
