### ISSUE TITLE
Loop to matrice

### ISSUE THREAD

**Issue by alsonicr** [LAAC-LSCP/ChildRecordsR#42]
Here is the list of loops that can be changed to a matrix

 - [convertor_long_cut.R](https://github.com/LAAC-LSCP/ChildRecordsR/blob/main/R/convertor_long_cut.R) l46:54
 - [LENA.overlap.R](https://github.com/LAAC-LSCP/ChildRecordsR/blob/main/R/LENA.overlap.R) l36:76
 - [extractDataCR.R](https://github.com/LAAC-LSCP/ChildRecordsR/blob/main/R/extractDataCR.R) l37:80
 - [find_rating_segment.R](https://github.com/LAAC-LSCP/ChildRecordsR/blob/main/R/find_rating_segment.R)
 - [aggregate.rating](https://github.com/LAAC-LSCP/ChildRecordsR/blob/main/R/aggregate_rating.R) l47:87
 - [compare.rating](https://github.com/LAAC-LSCP/ChildRecordsR/blob/main/R/raterComparaison.R) l47:97
 - [get.reliability](https://github.com/LAAC-LSCP/ChildRecordsR/blob/main/R/reliability.R) l28:47
 - [get.classification](https://github.com/LAAC-LSCP/ChildRecordsR/blob/main/R/SDT_raterData.R) l38

referred issue : #20

**Comment by alecristia** [comment]
https://github.com/LAAC-LSCP/ChildRecordsR/pull/46
