### ISSUE TITLE
the presence of output/ inside alice/ causes ChildRecord() command to fail

### ISSUE THREAD

**Issue by alecristia** [LAAC-LSCP/ChildRecordsR#55]
There are two problems about this behavior, first that it assumes that annotations will be available locally and otherwise it fails. It shouldn't do that -- it should throw a warning if csvs are not readable.

The other is that it may be over-checking for consistency -- rather than loading all the raw & converted of all the folders inside annotation, perhaps it should focus only on converted.

**Comment by lucasgautheron** [comment]
I agree with all of this
ChildRecord should completely disregard raw annotations; also, it should not fail if a set is missing.
